#PRCTICING DATA TYPES

#INITIALIZING A STRING 
NAMES ="ZERSHA" 
#PRINT STATEMENT FOR GETTING DATA TYPE
print(type(NAMES))

#INITIALIZING A INTEGER
AGE = 19
#PRINT STATEMENT FOR GETTING DATA TYPE
print(type(AGE))

#INITIALIZING A FLOAT
PERCENTAGE = 98.9
#PRINT STATEMENT FOR GETTING DATA TYPE
print(type(PERCENTAGE))
