#PRCTICING DATA TYPES

"""TEXT TYPE : 
STRING (USED TO DISPLAY CHARACTERS STORED IN A VARIABLE)"""

#INITIALIZING A STRING (WITH DOUBLE QUOTES)
NAMES ="ZERSHA"
#PRINTINT THE STRING
print(NAMES) 
#PRINT STATEMENT FOR GETTING DATA TYPE
print(type(NAMES))

#INITIALIZING A STRING (WITH SINGLE QUOTES)
FAV_COLOR = 'RED'
#PRINTING THE STRING
print(FAV_COLOR)
#PRINT STATEMENT FOR GETTING DATA TYPE
print(type(FAV_COLOR))

"""NUMERIC TYPE : 
INEGER  (USED TO DISPLAY SIMPLE NUMBERS ) ,
FLOAT   (USED TO DISPLAY DESIMAL NUMBERS ) , 
COMPLEX (USED TO DISPLAY NUMBERS BOTH IMAGINARY AND REAL PARTS )"""

#INITIALIZING A INTEGER
AGE = 19
#PRINTING THE INTEGER
print(AGE)
#PRINT STATEMENT FOR GETTING DATA TYPE
print(type(AGE))

#INITIALIZING A FLOAT
PERCENTAGE = 98.9
#PRINTING THE FLOAT
print(PERCENTAGE)
#PRINT STATEMENT FOR GETTING DATA TYPE
print(type(PERCENTAGE))

#INITIALIZAING A COMPLEX
COMPLEX = 1+2j
#PRINTING THE COMPLEX
print(COMPLEX)
#PRINT STATEMENT FOR GETTING DATA TYPE
print(type(COMPLEX))

"""Sequence Types :
LIST  (STROING VARIABLES THAT IS MUTABLE) ,
RANGE (A SEQUENCE OF NUMBER)"""

#INITIALIZING A LIST
LIST_OF_FRIENDS = ["ABBIA" , "FALAK" , "AMBREEN"]
#PRINT STATEMENT FOR THE LIST
print(LIST_OF_FRIENDS)
#PRINT STATEMENT OF GETTING DATA TYPE
print(type(LIST_OF_FRIENDS))

#INITIALIZING A RANGE
RANGE = range(5)
print(RANGE)
#PRINT STATEMENT OF GETTING DATA TYPE
print(type(RANGE))
