# USING STRING CONCATINATION
#VARIABLE 1 STORING FIRST STRING
First_Name = "ZERSHA"
#VARIABLE 2 STORING 2ND STRING
Last_Name = "MUZAMAL"
#USING STRING CONCATENATION
FULL_NAME = First_Name + Last_Name 
#PRINTING CONCATENATED STRING
print(FULL_NAME)

#Example 2 
#VARIABLE 1 STORING FIRST STRING
STUDENT_1 = "ZERSHA"
#VARIABLE 2 STORING 2ND STRING
STUDENT_2 = "FALAK"
#VARIABLE 3 STORING 3RD STRING
STUDENT_3 = "AMBREEN"
#USING STRING CONCATENATION 
TOP_3_STUDENTS = STUDENT_1 +" "+ STUDENT_2 +" "+STUDENT_3
#PRINTING CONCATENATED AND ONE MORE STRING 
print(TOP_3_STUDENTS , "THE TOPPER IS " , STUDENT_1)
