#ASKING FOR USER INPUT

#SIMPLE NAME INPUT FROM USER
NAME = input("ENTER YOUR NAME HERE:")
#PRINTING INPUT GIVEN BY THE USER
print(NAME)

#ASKING USER INPUT TO RUN THE IF ELSE STATEMENT
age = int(input("ENTER YOUR AGE HERE:"))
if age <=18:
    print("YOU CAN GET DISCOUNT")
else:
    print("you are to old to get it")
