"""QUESTION
Write three strings in different variables and print the output as one string."""
#SOLUTION:

#INITIALIZING FIRST VARIABLE AS DATATYPE STRING
STRING_1 = "WELCOME"
#INITIALIZING 2ND VARIABLE AS DATATYPE STRING
STRING_2 = "TO"
#INITIALIZING 3RD VARIABLE AS DATATYPE STRING
STRING_3 = "BATHSPA"
#PRINTING THE VARIABLES WITH A DASH IN BETWEEN THROUGH STRING CONCATINATION
print(STRING_1 + "-" + STRING_2 + "-" + STRING_3)  
