#QUESTION
"""Use a variable to represent your favorite number. Then, using that variable, create a
message that reveals your favorite number. Print that message."""
#ANSWER
#INITIALIZING A VARIABLE AND STORING A STRING IN IT
MESSAGE = "I JUST CLAIMED MY SOLO LEARN INTRODUCTION CERTIFICATE "
#PRINTING THE STATEMENT
print(MESSAGE)
#STORING THE UPDATED VALUE IN THE INITIALIZED VARIABLE
MESSAGE = "NOW I CLAIMED MY SOLO LEARN INTRODUCTION AND INTERMEDIATE CERTIFICATE"
#PRINTING THE UPDATED MESSAGE 
print(MESSAGE)
